<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lc4j_1190</groupId>
        <artifactId>lc4j-1190</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>lc4j-01hello</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>lc4j-01hello</name>
    <description>lc4j-01hello</description>

    <dependencies>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai-spring-boot4-starter</artifactId>
        </dependency>
    </dependencies>


</project>
