<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.springai2</groupId>
        <artifactId>spring-ai2</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>sa2-02streamchat</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>sa2-02streamchat</name>
    <description>sa2-02streamchat 流式聊天</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-openai</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-client-chat</artifactId>
        </dependency>

    </dependencies>

</project>
