<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.lc4j_1190</groupId>
    <artifactId>lc4j-1190</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>lc4j-1190</name>
    <description>langchain4j版本：1.19.0，2026年8月20日19:56:14</description>
    <packaging>pom</packaging>

    <properties>
        <java.version>25</java.version>
        <langchain4j.version>1.19.0</langchain4j.version>
    </properties>

    <modules>
        <module>lc4j-01hello</module>
        <module>lc4j-02streamchat</module>
        <module>lc4j-03chatmemory</module>
        <module>lc4j-04aiservice</module>
        <module>lc4j-05tool</module>
        <module>lc4j-06agent</module>
        <module>lc4j-06agent2</module>
        <module>lc4j-06agent3</module>
        <module>lc4j-07rag-1easy</module>
        <module>lc4j-07rag-2naive</module>
        <module>lc4j-07rag-3advanced</module>
        <module>lc4j-08javamcp</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--            mcp 服务端-->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-community-bom</artifactId>
                <version>1.19.0-beta29</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

    </dependencies>


</project>
