<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lc4j_1190</groupId>
        <artifactId>lc4j-1190</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>lc4j-08javamcp</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>lc4j-08javamcp</name>
    <description>lc4j-08javamcp 一个简单的stdio java mcp</description>

    <dependencies>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-mcp-server</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>my-first-mcp-server</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.Lc4j08javamcpApplication</mainClass>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
